config/routes.rb
PhotoPortfolio::Application.routes.draw do
  devise_for :users
  resources :albums, path: 'admin/albums' do
    collection do
      post :sort
    end
  end
  resources :photos, path: 'admin/photos' do
    collection do
      post :sort
    end
    member do
      get :publish_on_facebook
      get :refresh_from_facebook
    end
  end
  resources :lenses, path: 'admin/lenses'
  resources :lens, path: 'admin/lenses'
  resources :cams, path: 'admin/cams'
  get 'admin' => 'photos#index'

  get 'api/cams' => 'api#cams'
  get 'api/lenses' => 'api#lenses'
  get 'api/photos' => 'api#photos'
  get 'api/albums' => 'api#albums'

  get 'photo' => 'application#frontend'
  get 'photo/:album_id' => 'application#frontend'
  get 'photo/:album_id/:photo_id' => 'application#frontend'
  get 'about' => 'application#frontend'
  get 'contact' => 'application#frontend'

  root 'application#frontend'

end

app/controllers/lenses_controller.rb
class LensesController < ApplicationController
  before_action :set_lens, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  # GET /lenses
  # GET /lenses.json
  def index
    @lenses = Lens.all
  end

  # GET /lenses/1
  # GET /lenses/1.json
  # def show
  # end

  # GET /lenses/new
  def new
    @lens = Lens.new
  end

  # GET /lenses/1/edit
  def edit
  end

  # POST /lenses
  # POST /lenses.json
  def create
    @lens = Lens.new(lens_params)

    respond_to do |format|
      if @lens.save
        format.html { redirect_to lenses_url, notice: 'Lens was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lens }
      else
        format.html { render action: 'new' }
        format.json { render json: @lens.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lenses/1
  # PATCH/PUT /lenses/1.json
  def update
    respond_to do |format|
      if @lens.update(lens_params)
        format.html { redirect_to lenses_url, notice: 'Lens was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lens.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lenses/1
  # DELETE /lenses/1.json
  def destroy
    @lens.destroy
    respond_to do |format|
      format.html { redirect_to lenses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lens
      @lens = Lens.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lens_params
      params.require(:lens).permit(:name)
    end
end

app/helpers/lenses_helper.rb
module LensesHelper
end

app/views/lenses/_form.html.haml
= form_for @lens do |f|
  - if @lens.errors.any?
    #error_explanation
      %h2= "#{pluralize(@lens.errors.count, "error")} prohibited this len from being saved:"
      %ul
        - @lens.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .actions
    = f.submit 'Save', class: 'btn btn-success'

app/views/lenses/edit.html.haml
%h1 Editing len

= render 'form'

app/views/lenses/index.html.haml
%h1 Listing lenses

%table.table
  - @lenses.each do |lens|
    %tr
      %td.ncol= lens.name
      %td.acol
        %span.btn.btn-xs.btn-default
          %span.glyphicon.glyphicon-sort
        = link_to 'Edit', edit_len_path(lens), class: 'btn btn-xs btn-primary'
        = link_to 'Destroy', lens, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-xs btn-danger'

= link_to 'New Lens', new_len_path, class: 'btn btn-success'

app/views/lenses/new.html.haml
%h1 New len

= render 'form'