config/routes.rb
PhotoPortfolio::Application.routes.draw do
  devise_for :users
  resources :albums, path: 'admin/albums' do
    collection do
      post :sort
    end
  end
  resources :photos, path: 'admin/photos' do
    collection do
      post :sort
    end
    member do
      get :publish_on_facebook
      get :refresh_from_facebook
    end
  end
  resources :lenses, path: 'admin/lenses'
  resources :lens, path: 'admin/lenses'
  resources :cams, path: 'admin/cams'
  get 'admin' => 'photos#index'

  get 'api/cams' => 'api#cams'
  get 'api/lenses' => 'api#lenses'
  get 'api/photos' => 'api#photos'
  get 'api/albums' => 'api#albums'

  get 'photo' => 'application#frontend'
  get 'photo/:album_id' => 'application#frontend'
  get 'photo/:album_id/:photo_id' => 'application#frontend'
  get 'about' => 'application#frontend'
  get 'contact' => 'application#frontend'

  root 'application#frontend'

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos
  
  default_scope order 'position desc'
  
  def self.sort(ids)
    transaction do
      ids.each_with_index do |id, index|
        index = ids.count - index
        find(id).update_attribute(:position, index + 1)
      end
    end
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  # def show
  # end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        maximumPosition = Album.maximum('position')
        maximumPosition = 0 unless maximumPosition.present?
        @album.update position: maximumPosition + 1

        if Rails.env.production?
          me = FbGraph::User.me current_user.access_token
          album = me.album! name: @album.name
          @album.update facebook_id: album.raw_attributes['id']
        end

        format.html { redirect_to albums_url, notice: 'Album was successfully created.' }
        format.json { render action: 'show', status: :created, location: @album }
      else
        format.html { render action: 'new' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to albums_url, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  def sort
    Album.sort params[:ids].split(',')
    render text: 1
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :description, :position)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.haml
= form_for @album do |f|
  - if @album.errors.any?
    #error_explanation
      %h2= "#{pluralize(@album.errors.count, "error")} prohibited this album from being saved:"
      %ul
        - @album.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .actions
    = f.submit 'Save', class: 'btn btn-success'

app/views/albums/edit.html.haml
%h1 Editing album

= render 'form'

app/views/albums/index.html.haml
%h1 Listing albums

%table.table{'data-sort-url' => sort_albums_path}
  - @albums.each do |album|
    %tr{'data-id' => album.id}
      %td.ncol= album.name
      %td
        - if album.facebook_id.present?
          = link_to 'FB', "https://www.facebook.com/karenishe/media_set?set=a.#{album.facebook_id}", target: '_blank', class: 'btn btn-xs btn-info'
      / %td= album.description
      / %td= album.position
      %td.acol
        %span.btn.btn-xs.btn-default
          %span.glyphicon.glyphicon-sort
        = link_to 'Edit', edit_album_path(album), class: 'btn btn-xs btn-primary'
        = link_to 'Destroy', album, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-xs btn-danger'

= link_to 'New Album', new_album_path, class: 'btn btn-success'

app/views/albums/new.html.haml
%h1 New album

= render 'form'