config/routes.rb
PhotoPortfolio::Application.routes.draw do
  devise_for :users
  resources :albums, path: 'admin/albums' do
    collection do
      post :sort
    end
  end
  resources :photos, path: 'admin/photos' do
    collection do
      post :sort
    end
    member do
      get :publish_on_facebook
      get :refresh_from_facebook
    end
  end
  resources :lenses, path: 'admin/lenses'
  resources :lens, path: 'admin/lenses'
  resources :cams, path: 'admin/cams'
  get 'admin' => 'photos#index'

  get 'api/cams' => 'api#cams'
  get 'api/lenses' => 'api#lenses'
  get 'api/photos' => 'api#photos'
  get 'api/albums' => 'api#albums'

  get 'photo' => 'application#frontend'
  get 'photo/:album_id' => 'application#frontend'
  get 'photo/:album_id/:photo_id' => 'application#frontend'
  get 'about' => 'application#frontend'
  get 'contact' => 'application#frontend'

  root 'application#frontend'

end

app/models/cam.rb
class Cam < ActiveRecord::Base
  has_many :photos
end

app/controllers/cams_controller.rb
class CamsController < ApplicationController
  before_action :set_cam, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  # GET /cams
  # GET /cams.json
  def index
    @cams = Cam.all
  end

  # GET /cams/1
  # GET /cams/1.json
  # def show
  # end

  # GET /cams/new
  def new
    @cam = Cam.new
  end

  # GET /cams/1/edit
  def edit
  end

  # POST /cams
  # POST /cams.json
  def create
    @cam = Cam.new(cam_params)

    respond_to do |format|
      if @cam.save
        format.html { redirect_to cams_url, notice: 'Cam was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cam }
      else
        format.html { render action: 'new' }
        format.json { render json: @cam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cams/1
  # PATCH/PUT /cams/1.json
  def update
    respond_to do |format|
      if @cam.update(cam_params)
        format.html { redirect_to cams_url, notice: 'Cam was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cams/1
  # DELETE /cams/1.json
  def destroy
    @cam.destroy
    respond_to do |format|
      format.html { redirect_to cams_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cam
      @cam = Cam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cam_params
      params.require(:cam).permit(:name)
    end
end

app/helpers/cams_helper.rb
module CamsHelper
end

app/views/cams/_form.html.haml
= form_for @cam do |f|
  - if @cam.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cam.errors.count, "error")} prohibited this cam from being saved:"
      %ul
        - @cam.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .actions
    = f.submit 'Save', class: 'btn btn-success'

app/views/cams/edit.html.haml
%h1 Editing cam

= render 'form'

app/views/cams/index.html.haml
%h1 Listing cams

%table.table
  - @cams.each do |cam|
    %tr
      %td.ncol= cam.name
      %td.acol
        %span.btn.btn-xs.btn-default
          %span.glyphicon.glyphicon-sort
        = link_to 'Edit', edit_cam_path(cam), class: 'btn btn-xs btn-primary'
        = link_to 'Destroy', cam, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-xs btn-danger'

= link_to 'New Cam', new_cam_path, class: 'btn btn-success'

app/views/cams/new.html.haml
%h1 New cam

= render 'form'