config/routes.rb
PhotoPortfolio::Application.routes.draw do
  devise_for :users
  resources :albums, path: 'admin/albums' do
    collection do
      post :sort
    end
  end
  resources :photos, path: 'admin/photos' do
    collection do
      post :sort
    end
    member do
      get :publish_on_facebook
      get :refresh_from_facebook
    end
  end
  resources :lenses, path: 'admin/lenses'
  resources :lens, path: 'admin/lenses'
  resources :cams, path: 'admin/cams'
  get 'admin' => 'photos#index'

  get 'api/cams' => 'api#cams'
  get 'api/lenses' => 'api#lenses'
  get 'api/photos' => 'api#photos'
  get 'api/albums' => 'api#albums'

  get 'photo' => 'application#frontend'
  get 'photo/:album_id' => 'application#frontend'
  get 'photo/:album_id/:photo_id' => 'application#frontend'
  get 'about' => 'application#frontend'
  get 'contact' => 'application#frontend'

  root 'application#frontend'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  belongs_to :cam
  belongs_to :lens
  
  has_many :photo_facebook_users, dependent: :destroy
  has_many :facebook_users, through: :photo_facebook_users
  has_many :facebook_comments, dependent: :destroy

  has_attached_file :image, styles: {
    preview: '70x70>',
    thumb: '320x320#',
    thumb_retina: '640x640#',
    normal: Proc.new { |instance| instance.resize_image('normal') }, # 1280x800
    large: Proc.new { |instance| instance.resize_image('large') }, # 2560x1600 or Retina 13"
    xlarge: Proc.new { |instance| instance.resize_image('xlarge') } # Retina 15"
  }, convert_options: {
    thumb: '-quality 80',
    thumb_retina: '-quality 80',
    normal: '-quality 80',
    large: '-quality 80',
    xlarge: '-quality 80'
  },
    default_url: '/images/:style/missing.png',
    path: ':rails_root/:maybe_public/i/:hash/i.:extension',
    url: '/i/:hash/i.:extension',
    hash_data: ':class/:attachment/:id/:style/:updated_at',
    hash_secret: 'n8t&T*&RfyoF&*(OWYf89wheF:HWOEIfh9348ytg9h34ofpO*HW$389g9347y5gf79eghpergoe;kghe)rghr@$R@2e'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  default_scope order 'position desc'
  
  after_post_process :load_exif
  
  # paginates_per 10
  
  def thumb_url
    self.image.url :thumb, timestamp: false
  end
  def thumb_x2_url
    self.image.url :thumb_retina, timestamp: false
  end
  def normal
    self.image.url :normal, timestamp: false
  end
  def large
    self.image.url :large, timestamp: false
  end
  def xlarge
    self.image.url :xlarge, timestamp: false
  end

  def resize_image(style)
    path = image.queued_for_write[:original].path
    geo = Paperclip::Geometry.from_file(path)

    case style
    when 'normal'
      if geo.horizontal?
        '1281x854#'
      else
        '854x1281#'
      end
    when 'large'
      if geo.horizontal?
        '2562x1708#'
      else
        '1708x2562#'
      end
    when 'xlarge'
      if geo.horizontal?
        '2880x1920#'
      else
        '1920x2880#'
      end
    end
  end

  def self.sort(ids)
    transaction do
      ids.each_with_index do |id, index|
        index = ids.count - index
        find(id).update_attribute(:position, index + 1)
      end
    end
  end


  def load_exif
    exif = EXIFR::JPEG.new(image.queued_for_write[:original].path)
    return if exif.nil? or not exif.exif?
    begin
      self.exposure = exif.exposure_time.to_s.gsub /\/1$/, ''
      self.aperture = exif.f_number.to_f
      self.focal_distance = exif.focal_length.to_i
      self.iso = exif.iso_speed_ratings.to_i
      self.date = exif.date_time.to_date
    rescue
      false
    end
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy, :publish_on_facebook, :refresh_from_facebook]

  layout 'admin'
  
  require 'open-uri'

  def publish_on_facebook
    if Rails.env.production?
      me = FbGraph::User.me current_user.access_token
      album = FbGraph::Album.new @photo.album.facebook_id, access_token: current_user.access_token
      photo = album.photo!(
        access_token: current_user.access_token,
        source: File.new(@photo.image.path(:normal)),
        message: "#{@photo.name.upcase}\n\n #{@photo.description}\n http://#{Rails.application.config.host_name}/photo/all/#{@photo.id}"
      )
      @photo.update facebook_id: photo.raw_attributes['id']
      redirect_to photos_url, notice: 'Photo was successfully published to Facebook.'
    else
      redirect_to photos_url, notice: 'Looks like you are not in production environment.'
    end
  end
  
  def refresh_from_facebook
    if Rails.env.production?

      if @photo.facebook_id.present?
        me = FbGraph::User.me current_user.access_token
        photo = FbGraph::Photo.new @photo.facebook_id, access_token: current_user.access_token

        @photo.facebook_users = []
        likes = photo.likes
        while likes.count > 0
          save_likes likes, @photo
          likes = likes.next
        end
        @photo.update likes: @photo.facebook_users.count

        @photo.facebook_comments.destroy_all
        comments = photo.comments
        while comments.count > 0
          save_comments comments, @photo
          comments = comments.next
        end
        @photo.update comments: @photo.facebook_comments.count
      end

      if @photo.photosight_url.present?
        pageIO = open @photo.photosight_url
        pageData = pageIO.read
        
        plusCount = 0
        
        plus = pageData.scan /<span id="recommendations_[^"]*" class="result">([\d]*)<\/span>/i
        plus.each { |pl| plusCount += pl[0].to_i }

        minus = pageData.scan /<span id="negative_marks_count_s" class="result">([\d]*)<\/span>/i
        minus.each { |mn| plusCount -= mn[0].to_i }
        
        @photo.update likes: (@photo.facebook_users.count + plusCount)
        
        comments = pageData.scan /class="commenttext"/i
        @photo.update comments: (@photo.facebook_comments.count + comments.count)
        
      end

      redirect_to photos_url, notice: 'Photo data was successfully refreshed from Facebook and/or Photosight.'
    else
      redirect_to photos_url, notice: 'Looks like you are not in production environment.'
    end
  end

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
    # @photos = @photos.where(album_id: params[:album_id]) if params.has_key? :album_id
    # @photos = @photos.page params[:page]
  end

  # GET /photos/1
  # GET /photos/1.json
  # def show
  # end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        maximumPosition = Photo.maximum('position')
        maximumPosition = 0 unless maximumPosition.present?
        @photo.update position: maximumPosition + 1
        format.html { redirect_to photos_url, notice: 'Photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photos_url, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  def sort
    Photo.sort params[:ids].split(',')
    render text: 1
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:name, :description, :position, :views, :cam_id, :lens_id, :iso, :aperture, :exposure, :focal_distance, :image, :date, :album_id, :photosight_url)
    end
    
    def save_likes (likes, _photo)
      likes.each do |user|
        facebookUser = FacebookUser.find_by_identifier user.identifier
        facebookUser = FacebookUser.create(identifier: user.identifier, name: user.name) unless facebookUser.present?
        begin
          _photo.facebook_users << facebookUser
        rescue
          true
        end
      end
    end
    
    def save_comments (comments, _photo)
      comments.each do |comment|
        facebookUser = FacebookUser.find_by_identifier comment.from.identifier
        facebookUser = FacebookUser.create(identifier: comment.from.identifier, name: comment.from.name) unless facebookUser.present?
        facebookComment = FacebookComment.find_by_identifier comment.identifier
        facebookComment = FacebookComment.create(identifier: comment.identifier, facebook_user_id: facebookUser.id, photo_id: _photo.id, created_at: comment.created_time, message: comment.message) unless facebookComment.present?
      end
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.haml
= form_for @photo do |f|
  - if @photo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:"
      %ul
        - @photo.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label 'Image'
    - if @photo.image.present?
      %br
      = image_tag(@photo.image.url(:preview))
    = f.file_field :image
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :album
    = collection_select :photo, :album_id, Album.all, :id, :name, {}, {class: 'chosen', width: '100%'}
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .form-group
    = f.label :date
    = f.text_field :date, class: 'form-control', type: 'date'
  .form-group
    = f.label :cam
    = collection_select :photo, :cam_id, Cam.all, :id, :name, {}, {class: 'chosen', width: '100%'}
  .form-group
    = f.label :lens
    = collection_select :photo, :lens_id, Lens.all, :id, :name, {}, {class: 'chosen', width: '100%'}
  .form-group
    = f.label 'ISO (100–6400)'
    = f.number_field :iso, class: 'form-control'
  .form-group
    = f.label 'Aperture (f11)'
    = f.text_field :aperture, class: 'form-control'
  .form-group
    = f.label 'Exposure (1/10s)'
    = f.text_field :exposure, class: 'form-control'
  .form-group
    = f.label 'Focal distance (34mm)'
    = f.number_field :focal_distance, class: 'form-control'
  .form-group
    = f.label 'Photosight URL'
    = f.text_field :photosight_url, class: 'form-control'
  .actions
    = f.submit 'Save', class: 'btn btn-success'

app/views/photos/edit.html.haml
%h1 Editing photo

= render 'form'

app/views/photos/index.html.haml
%h1 Listing photos

%table.table{'data-sort-url' => sort_photos_path}
  - @photos.each do |photo|
    %tr{'data-id' => photo.id}
      %td.ncol
        - if photo.name.present?
          = photo.name
        - else
          %span.label.label-warning No name
      / %td= photo.description
      / %td= photo.views
      %td
        - if photo.album.present?
          = photo.album.name
        - else
          %span.label.label-warning No album
      %td= photo.cam.name if photo.cam.present?
      %td= photo.lens.name if photo.lens.present?
      %td
        - if photo.iso != 0
          = "ISO #{photo.iso}"
        - else
          %span.label.label-warning ISO 0
      %td
        - if photo.aperture != 0
          = "f#{photo.aperture}"
        - else
          %span.label.label-warning f0
      %td
        - if photo.exposure.present?
          = "#{photo.exposure}s"
        - else
          %span.label.label-warning 0s
      %td
        - if photo.focal_distance != 0
          = "#{photo.focal_distance}mm"
        - else
          %span.label.label-warning 0mm
      %td
        - if photo.date.present?
          = photo.date
        - else
          %span.label.label-warning No date
      %td
        - if photo.facebook_id.present?
          = link_to 'FB', "https://www.facebook.com/photo.php?fbid=#{photo.facebook_id}", target: '_blank', class: 'btn btn-xs btn-info'
        - else
          = link_to 'Publish', publish_on_facebook_photo_path(photo), class: 'btn btn-xs btn-success'
        - if photo.photosight_url.present?
          = link_to 'PS', photo.photosight_url, target: '_blank', class: 'btn btn-xs btn-default'
      %td.icol= image_tag photo.image.url :preview
      %td.acol
        %span.btn.btn-xs.btn-default
          %span.glyphicon.glyphicon-sort
        = link_to 'Edit', edit_photo_path(photo), class: 'btn btn-xs btn-primary'
        = link_to 'Destroy', photo, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-xs btn-danger'
        %hr.shr
        - if photo.facebook_id.present? or photo.photosight_url.present?
          %i.fa.fa-thumbs-up
          .sm= photo.likes
          %i.fa.fa-comments
          .sm= photo.comments
          = link_to '<i class="fa fa-refresh"></i>'.html_safe, refresh_from_facebook_photo_path(photo), class: 'btn btn-xs btn-info'

= link_to 'New Photo', new_photo_path, class: 'btn btn-success'

app/views/photos/new.html.haml
%h1 New photo

= render 'form'